# Stage 1: Build the Angular application
FROM node:20-alpine as build-step
WORKDIR /app

# Copy package files and install dependencies
# We use 'npm install' because your package manager is npm
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copy the rest of the frontend source code
COPY . .

# Run the build command defined in your package.json
RUN npm run build

# Stage 2: Serve the application using Nginx
FROM nginx:alpine
# Copy your custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Copy build files
COPY --from=build-step /app/dist/angular_assignment/browser /usr/share/nginx/html
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]